name: tea_app
description: "A new Flutter project."


publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  dio: ^5.4.2+1
  dartz: ^0.10.1
  bloc: ^8.1.4
  flutter_bloc: ^8.1.5  
  freezed_annotation: ^2.4.1
  flutter_modular: ^6.3.2
  page_transition: ^2.1.0


  cupertino_icons: ^1.0.2
  flutter_svg: ^2.0.10+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.4.9  
  freezed: ^2.4.7

  flutter_lints: ^2.0.0

flutter:

  assets:
   - assets/svg/

  uses-material-design: true

  
  
  
  

  
  

  
  

  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
  
